### ISSUE TITLE
What is the difference between xqau51 and xqau52?

### ISSUE THREAD

**Issue by AngryGami** [sonyxperiadev/device-sony-pdx201#7]
Are these different hardware sets and how to understand which device I have at hands?

**Comment by MarijnS95** [comment]
The difference between these files should tell?

https://github.com/sonyxperiadev/device-sony-pdx201/blob/e71a972bbb862e4df1abf34b6ed9a7a8135565f3/aosp_xqau52.mk#L15-L16

**Comment by AngryGami** [comment]
Thanks
